[package]
name = "piet"
version = "0.1.0"
edition = "2018"

[dependencies]
parse = { version = "0.1.0", path = "parse" }
interpret = { version = "0.1.0", path = "interpret" }
clap = "3.0.0-beta.2"

[workspace]
members = ["parse", "interpret"]

