[package]
name = "piet"
version = "0.1.0"
edition = "2018"

[dependencies]
piet-io = { version = "0.1.0", path = "piet-io" }
piet-interpreter = { version = "0.1.0", path = "piet-interpreter" }
image = "0.23.14"
clap = "3.0.0-beta.2"

[workspace]
members = ["piet-io", "piet-interpreter"]

