max_width = 100
fn_call_width = 80
struct_lit_width = 80
struct_variant_width = 80
fn_brace_style = "PreferSameLine"
item_brace_style = "PreferSameLine"
fn_single_line = false
array_width = 80
chain_one_line_max = 80
single_line_if_else_max_width = 80

wrap_comments = true
comment_width = 100

match_block_trailing_comma = true

